#!/bin/bash

# Use the same regexp as shown in "man urlview".
grep -oP '(((http|https|ftp|gopher)|mailto):(//)?[^ <>"\t]*|'\
'(www|ftp)[0-9]?\.[-a-z0-9.]+)[^ .,;\t\n\r<">\):]?[^, <>"\t]*'\
'[^ .,;\t\n\r<">\):]' "$@"


#Thanks to https://github.com/vain/bin-pub/blob/master/urlview2
